version: '3.8'

services:
  remindmine:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDMINE_URL=${REDMINE_URL}
      - REDMINE_API_KEY=${REDMINE_API_KEY}
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3.2}
      - CHROMADB_PATH=/app/data/chromadb
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - UPDATE_INTERVAL_MINUTES=${UPDATE_INTERVAL_MINUTES:-60}
    volumes:
      - ./data:/app/data
    depends_on:
      - ollama
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    # Uncomment the following lines if you have NVIDIA GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  ollama_data:
