version: '3.8'

services:
  redmine_db:
    image: mysql:8.0
    container_name: redmine_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: redmine_root
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine_password
    volumes:
      - redmine_db_data:/var/lib/mysql
    networks:
      - redmine_network
    ports:
      - "3306:3306"

  redmine:
    image: redmine:5.1
    container_name: redmine_app
    restart: unless-stopped
    depends_on:
      - redmine_db
    environment:
      REDMINE_DB_MYSQL: redmine_db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine_password
      REDMINE_SECRET_KEY_BASE: supersecretkey123456789abcdef
    volumes:
      - redmine_files:/usr/src/redmine/files
      - redmine_plugins:/usr/src/redmine/plugins
      - redmine_themes:/usr/src/redmine/public/themes
    ports:
      - "3001:3000"
    networks:
      - redmine_network

volumes:
  redmine_db_data:
  redmine_files:
  redmine_plugins:
  redmine_themes:

networks:
  redmine_network:
    driver: bridge
